Vagrant.require_version ">= 2.2.15"

$install_system_pkg = <<-SCRIPT
  apt update && \
  apt upgrade -y && \
  apt install -y vim curl rsync wget net-tools telnet dnsutils build-essential unzip && \
  apt autoremove -y
SCRIPT

$mysql_install = <<-SCRIPT
  apt update && \
  apt upgrade -y && \
  apt install -y mysql-server python3-pip unzip && \
  apt autoremove -y
SCRIPT

$nginx_install = <<-SCRIPT
  apt update && \
  apt upgrade -y && \
  apt install -y nginx php-fpm php-mysql php-curl python3-pip unzip && \
  apt autoremove -y
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = true


#MySQL YoURLS
  config.vm.define "mysqldb" do |mysql|
    mysql.vm.hostname = "mysql-db01.rcarj.eu"
    mysql.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    mysql.vm.provision "shell", inline: $install_system_pkg
    mysql.vm.provision "shell", inline: $mysql_install
    mysql.vm.synced_folder "./mysql_files", "/opt/mysql_files"
    mysql.vm.provision "shell", inline: "mysql -sfu root < /opt/mysql_files/mysql_install.sql"
    mysql.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
        vb.name = "mysql-db01"
     end
  end

#Nginx YoURLS
  config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "nginx-web01.rcarj.eu"
    nginx.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    nginx.vm.provision "shell", inline: $install_system_pkg
    nginx.vm.provision "shell", inline: $nginx_install
    nginx.vm.synced_folder "./nginx_files", "/opt/nginx_files"
    nginx.vm.provision "shell", inline: "cat /opt/nginx_files/nginx.conf > /etc/nginx/nginx.conf"
    nginx.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
        vb.name = "nginx-web01"
     end
  end

end